language: rust
cache: cargo
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev
      - libiberty-dev
      - gcc
      - cmake # required for cargo-update
    sources:
      - kalakris-cmake

rust:
  - stable
  - beta
  - nightly
before_install:
  - bash $HOME/ci/travis/before_install.sh
before_script:
  - bash $HOME/ci/travis/install.sh
script:
  - |
      cargo build &&
      cargo test
  - cargo clippy
    
after_success:
  - cargo kcov --coveralls --lib --no-clean-rebuild -- --exclude-pattern=$HOME/.cargo

notifications:
  email:
    on_success: never