language: rust
cache: cargo
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev
      - libiberty-dev
      - gcc
      - cmake # required for cargo-update
    sources:
      - kalakris-cmake

before_install:
  # Required for running tests (for libclang.so)
  - chmod -R +x $TRAVIS_BUILD_DIR/ci/travis
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/clang-7.0.0/lib:target/debug/deps

before_script:
  - bash $TRAVIS_BUILD_DIR/ci/travis/install.sh
  - rustup component add clippy || true
  - cargo fmt -- --check

matrix:
  include:
    - rust:
      - stable
      - beta
      script:
        - |
            cargo build &&
            cargo test &&
            cargo clippy

    - rust: nightly
      script:
        - |
            cargo build &&
            cargo test
          
after_success:
  - cargo kcov --coveralls --lib --no-clean-rebuild -- --exclude-pattern=$HOME/.cargo
        
notifications:
  email:
    on_success: never